#!/usr/bin/env bash
set -euo pipefail

APPIMAGE_PATH=${1:-"./src-tauri/target/release/bundle/appimage/VocaDB Player_0.1.0_amd64.AppImage"}

export GDK_BACKEND="${GDK_BACKEND:-x11}"
export WINIT_UNIX_BACKEND="${WINIT_UNIX_BACKEND:-x11}"
export GDK_GL="${GDK_GL:-disable}"
export WEBKIT_DISABLE_COMPOSITING_MODE="${WEBKIT_DISABLE_COMPOSITING_MODE:-1}"
export WEBKIT_DISABLE_DMABUF_RENDERER="${WEBKIT_DISABLE_DMABUF_RENDERER:-1}"
export WEBKIT_DISABLE_ACCELERATED_2D_CANVAS="${WEBKIT_DISABLE_ACCELERATED_2D_CANVAS:-1}"
export WEBKIT_DISABLE_WEBGL="${WEBKIT_DISABLE_WEBGL:-1}"
export WEBKIT_DISABLE_SANDBOX="${WEBKIT_DISABLE_SANDBOX:-1}"
export WEBKIT_DISABLE_GPU_PROCESS="${WEBKIT_DISABLE_GPU_PROCESS:-1}"
export LIBGL_ALWAYS_SOFTWARE="${LIBGL_ALWAYS_SOFTWARE:-1}"
export SOUP_FORCE_HTTP1="${SOUP_FORCE_HTTP1:-1}"
export APPIMAGELAUNCHER_DISABLE="${APPIMAGELAUNCHER_DISABLE:-1}"
export GST_PLUGIN_SYSTEM_PATH_1_0="${GST_PLUGIN_SYSTEM_PATH_1_0:-/usr/lib/gstreamer-1.0}"
export GST_PLUGIN_PATH_1_0="${GST_PLUGIN_PATH_1_0:-/usr/lib/gstreamer-1.0}"
export GST_PLUGIN_SCANNER_1_0="${GST_PLUGIN_SCANNER_1_0:-/usr/lib/gstreamer-1.0/gst-plugin-scanner}"

exec "${APPIMAGE_PATH}"
